In [42]:
pip install -U scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [29]:
from sklearn.svm import SVC
from sklearn import datasets
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import *
from sklearn.neural_network import MLPClassifier

In [30]:
train_feature_vector = np.array([[1,2], [3,4], [1,0], [3,2]])
train_labels = np.array([1,1,0,0])
test_feature_vector = np.array([ [1,3],[3,5], [3,1] ])
test_labels = np.array([1,1,0])

In [31]:
classifier = SVC(kernel = 'linear') 

In [32]:
classifier.fit(train_feature_vector, train_labels)

SVC(kernel='linear')

In [33]:
SVCPredictions = classifier.predict(test_feature_vector)
print(SVCPredictions)
print(accuracy_score(test_labels,SVCPredictions))
print(precision_score(test_labels,SVCPredictions))
print(recall_score(test_labels,SVCPredictions))
print(f1_score(test_labels,SVCPredictions))

[1 1 0]
1.0
1.0
1.0
1.0


In [34]:
GNBclf = GaussianNB()
GNBclf.fit(train_feature_vector,train_labels)
GNBPredictions = GNBclf.predict(test_feature_vector)

In [35]:
print(GNBPredictions)
print(accuracy_score(test_labels,GNBPredictions))
print(precision_score(test_labels,GNBPredictions))
print(recall_score(test_labels,GNBPredictions))
print(f1_score(test_labels,GNBPredictions))

[1 1 0]
1.0
1.0
1.0
1.0


In [36]:
RFclassifier = RandomForestClassifier()

In [37]:
RFclassifier.fit(train_feature_vector, train_labels)

RandomForestClassifier()

In [38]:
RFPredictions = RFclassifier.predict(test_feature_vector)
print(RFPredictions)
print(accuracy_score(test_labels,RFPredictions))
print(precision_score(test_labels,RFPredictions))
print(recall_score(test_labels,RFPredictions))
print(f1_score(test_labels,RFPredictions))

[1 1 0]
1.0
1.0
1.0
1.0


In [49]:
mlpCLF = MLPClassifier(tol = 0.001, max_iter = 1000)

In [50]:
mlpCLF.fit(train_feature_vector, train_labels)

MLPClassifier(max_iter=1000, tol=0.001)

In [51]:
MLPPredictions = mlpCLF.predict(test_feature_vector)
print(MLPPredictions)
print(accuracy_score(test_labels,MLPPredictions))
print(precision_score(test_labels,MLPPredictions))
print(recall_score(test_labels,MLPPredictions))
print(f1_score(test_labels,MLPPredictions))

[1 1 0]
1.0
1.0
1.0
1.0


In [1]:
print("Hello")

Hello
